### PR TITLE
[ENH] Enable full plot range for fm.plot()

### LINKED ISSUE #245: [ENH]: Show full PSD when plotting PSD+model using fm.plot()
# Enhancement to improve FOOOF's plotting function for better visual inspection

## Current situation
The aperiodic component is often used in a narrow frequency range, for example, 30-50 Hz (Gao et al. 2017). 

When calling `fm.plot()`, the PSD and the fitted model are only shown in the fitting range (e.g. 30-50 Hz). However, to evaluate the fit visually, I find it essential to view the full PSD (e.g. 1-100 Hz). 

## Why not ideal
I emphasize the importance of this [with this code](https://github.com/fooof-tools/fooof/files/10030300/fooof_plotting_enh.pdf). For M/EEG researchers, the shown spectrum with the gigantic beta oscillation might look artificial. However, it actually perfectly resembles a true LFP signal obtained from a Parkinsonian subthalamic nucleus ([Gerster et al. 2022](https://doi.org/10.1007/s12021-022-09581-8)). When applying FOOOF and evaluating the fits, I was fooled into believing, that 30-45 Hz might be a good fit range for the aperiodic component (see the first figure provided by FOOOF). It took me some time plotting the full spectrum (second figure) to realize that I was actually fitting the beta peak instead of the aperiodic component! 

## Suggestion
I would suggest adding another keyword argument `freq_range` to `fm.plot(freq_range=None)`.

If `freq_range=None`, the plotted frequency range will be set to the fitting `freq_range=fit_range`, as currently. If `freq_range="full"`, the entire spectrum is plotted, and if `freq_range=(float1, float2)` the frequency range from float1 to float2 Hz will be plotted. 

It would be amazing to enable this keyword also in `fm.save_report()` as I usually check these reports to evaluate my fitting parameters.

### PR DESCRIPTION
**Pull request by moritz-gerster**
Fixes #245. With the new functionality, an inspection of fits with a narrow fitting range will be much more user-friendly. 

This kind of inspection was recommended in Gerster et al. (2022): [Challenge 2: Avoiding Oscillations Crossing Fitting Range Borders](https://doi.org/10.1007/s12021-022-09581-8).

For new behavior see the last two figures here: [Full_Plot_Range](https://github.com/fooof-tools/fooof/files/10034798/fooof_plotting_PR.pdf).

### CODE REVIEW

**Comment by TomDonoghue** [comment]
Hey @moritz-gerster - can you merge main branch into your branch? There was an issue with the CI, so I made some maintenance updates to get things back up and running.

**Comment by moritz-gerster** [comment]
> Hey @moritz-gerster - can you merge main branch into your branch? There was an issue with the CI, so I made some maintenance updates to get things back up and running.

Hey @TomDonoghue, I synced my fork, it should now be up to date!

**Comment by moritz-gerster** [comment]
@TomDonoghue let me know if I should change something about the PR such as for example adding some tests 👍

**Comment by moritz-gerster** [comment]
Hey @TomDonoghue, I'm happy to add some tests to the PR if you would consider it useful :)

**Comment by TomDonoghue** [comment]
Hey @moritz-gerster - thanks for opening a PR on this idea, and sorry for the delay - things have been busy, but we're picking up on some fooof development now. 

I added a broader set of notes on this topic in #245, and offered a different strategy in #276. Let me know what you think of that - if it looks good to you, it can replace this, and keep the object more lightweight. 

By the way, in terms of implementation, if we were to go this direction (storing the full spectrum in the object), I think that we would actually want to store a single copy of the broad range spectrum, and do something like use a masked array, or do an on-the-fly computation for extracting the fit range, rather than duplicating the arrays.

**Comment by moritz-gerster** [comment]
Agreed :)

**Comment by TomDonoghue** [comment]
Confirming - following discussion in #245 and #276, a different strategy to allow for the same functionality has now been merged in #276, so closing this PR! Thanks for the work @moritz-gerster - it helped get a cool new feature into the module!

**Pull request closed without merging**
