### PR TITLE
extend reports

### PR DESCRIPTION
**Pull request by mwprestonjr**
Addresses #256 by adding all arguments that can be passed to plts.fm.plot_fm().

### CODE REVIEW

**Comment by mwprestonjr** [comment]
The latter commit (6f185a6) addresses issue #258 .

**Comment by TomDonoghue** [comment]
Hey @mwprestonjr - thanks for digging into these ideas and creating the PR!

For #256 / adding plot arguments to report plot - I do agree that it would be nice to be able to customize the plots in the reports, and there's not really any reason not to allow this. 

Couple thoughts:
- The arguments would have to be added to `FOOOF.save_report` as well, right, in order to allow this when using the object method (which I take to be the standard method), rather than when using the separate function. 
- Because this leads to copied input parameters across multiple access point, I think I would suggest doing this by adding  a ``**plt_kwargs`` keyword input to `save_report _fm` and to `FOOOF.plot`. This would be better for maintenance - it means that the report allow for passing through all possible arguments, but they don't have to be individually noted in the report functions, and it means any updates to the plot function wouldn't have to worry about maintaining consistency with upstream use by the report functions. 

For #258 / saving individual model reports from a Group object, did you look at the `get_fooof` method on the group object? I think what you added largely replicates what can be done with that function. 

For example, saving a specified individual model from a group object should be do-able like this:
```fg.get_fooof(ind=index, regenerate=True).save_report()```

I think that should do the same as what you added? (I didn't try running and comparing the code, so let me know if there is some difference I'm not noticing). 

I do agree that the above code is not particularly obvious to be able to write out for the average user - so to make this more accessible, maybe FOOOFGroup should be given an extra convenience method for this, something like:
```
def save_model_report(self, index):
    """"Save out a model report for a specified index."""
    self.get_fooof(ind=index, regenerate=True).save_report()
```

**Comment by mwprestonjr** [comment]
Hey @TomDonoghue. Thanks for the quick response. 
For #256: I appreciate the feedback. I will implement this as suggested. 
For #258: I somehow missed this method. I think the save_model_report() is a great idea.

**Comment by TomDonoghue** [comment]
Hey @mwprestonjr - I just approved the tests to run, and there seems to be some issue - I think because I'm not sure you actually want to remove the `plot_kwargs` argument from the `plot_fm` function?

**Comment by mwprestonjr** [comment]
Yes, I think you're right. Adding it back now. I don't honestly understand why though.

**Review by TomDonoghue — APPROVED** [review]

**Comment by TomDonoghue** [comment]
Thanks for the work on this @mwprestonjr! Looks good!

I made a couple direct edits to merge this directly so we can include it in 1.1 (small clean ups and adding a test for the new `save_model_report`) - otherwise, everything looks great! Merging in now!

**Pull request merged**
